site_name: devin de araujo
site_author: Devin de Araujo <devindearaujo@gmail.com>
site_url: https://what-the-dev.github.io/dev.github.io/
repo_url: https://github.com/what-the-dev/
copyright: Copyright 2020 Devin de Araujo

theme:
  name: material
  palette: 
    #scheme: default
    primary: white
    accent: pink
  logo: images/dda.svg
  favicon: images/dda.svg

markdown_extensions:
  - codehilite


extra_css:
  - stylesheets/extra.css


plugins:
  - search
  #- mkdocs-jupyter
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
  #    enable_default_pandas_dataframe_styling: false


# footer socials
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/what-the-dev
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/devindearaujo/
